name: CI/CD Pipeline for File Sharing App

on:
  push:
    branches:
      - main

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install Dependencies
      run: |
        npm install

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.6

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: Extract and Display S3 Website URL
      id: extract_s3_url
      run: |
        echo "Extracting the S3 Website URL..."
        URL=$(terraform output -raw s3_website_url | sed 's/::.*//')
        echo "Website URL: http://$URL"
        echo "::set-output name=website_url::http://$URL"

    - name: Output Application Details
      run: |
        echo "Deployment Successful!"
        echo "Access your website at: ${{ steps.extract_s3_url.outputs.website_url }}"
