name: CI/CD Pipeline for File Sharing App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.6

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: Extract and Sanitize Outputs
      id: extract_outputs
      run: |
        echo "Extracting Terraform outputs..."
        S3_WEBSITE_URL=$(terraform output -raw s3_website_url | tr -d '\n\r')
        EC2_PUBLIC_IP=$(terraform output -raw ec2_public_ip | tr -d '\n\r')
        echo "S3_WEBSITE_URL=$S3_WEBSITE_URL" >> $GITHUB_ENV
        echo "EC2_PUBLIC_IP=$EC2_PUBLIC_IP" >> $GITHUB_ENV
        echo "::set-output name=s3_website_url::$S3_WEBSITE_URL"
        echo "::set-output name=ec2_public_ip::$EC2_PUBLIC_IP"

    - name: Output Deployment Details
      run: |
        echo "S3 Website URL: ${{ env.S3_WEBSITE_URL }}"
        echo "EC2 Public IP: ${{ env.EC2_PUBLIC_IP }}"
